name: User Story
description: Create a User Story
title: ""
labels: ["type:user-story"]

body:
  - type: textarea
    id: description
    attributes:
      label: Description
      placeholder: "Add description"
    validations:
      required: true

  - type: textarea
    id: acceptance_criteria
    attributes:
      label: Acceptance Criteria
      placeholder: "Add Acceptance Criteria"

  - type: textarea
    id: discussion
    attributes:
      label: Discussion
      placeholder: "Add a comment. Use # to link an issue, @ to mention a person, ! to link a pull request"

  - type: dropdown
    id: priority
    attributes:
      label: Priority
      options:
        - "1"
        - "2"
        - "3"
        - "4"
    validations:
      required: true

  - type: input
    id: story_points
    attributes:
      label: Story Points
      placeholder: "1, 2, 3, 5, 8"

  - type: dropdown
    id: risk
    attributes:
      label: Risk
      options:
        - "3-Low"
        - "2-Medium"
        - "1-High"
