name:  User Story
description: Create a User Story
title: "Enter Title "
labels: ["type:user-story"]

body:
  - type: textarea
    id: description
    attributes:
      label: Description
      description: Add description
    validations:
      required: true

  - type: textarea
    id: acceptance_criteria
    attributes:
      label: Acceptance Criteria
      description: Add Acceptance Criteria
      value: |
        - [ ] Criteria 1
        - [ ] Criteria 2
        - [ ] Criteria 3
    validations:
      required: true

  - type: textarea
    id: discussion
    attributes:
      label: Discussion
      description: >
        Add a comment.Use # to link an issue, @ to mention a person,! to link a pull request

  - type: dropdown
    id: priority
    attributes:
      label: Priority
      options:
        - "1"
        - "2"
        - "3"
        - "4"
    validations:
      required: true

  - type: input
    id: story_points
    attributes:
      label: Story Points
      placeholder: "1, 2, 3, 5, 8"

  - type: dropdown
    id: risk
    attributes:
      label: Risk
      options:
        - "Low"
        - "Medium"
        - "High"
